### PR TITLE
populating voice repo

### PR DESCRIPTION
**Pull request by ghost**
Added:
-Android Application
-Python Script
-Collected Data

Will be using this repository from now on

### CODE REVIEW

**Comment by iantrich** [comment]
You should probably look to remove the Android Studio specific files from the repo (*/.idea, .iml) they might cause problems for others cloning the repo as Android Studio for Mac vs Windows vs Linux use the files differently.

**Comment by ghost** [comment]
Will do.

**Comment by ghost** [comment]
If I add those .idea/ and *.iml to the gitignore, then recommit/push, will
that fix the problem?

**Comment by iantrich** [comment]
I think you'll need to delete them from the repo and then add them to
ignore. You can do this by editing the .gitignore and then running from the
command line:

git ls-files -ci --exclude-standard -z | xargs -0 git rm --cached

That should keep the files on your your disk but remove them from the repo.
Source
http://stackoverflow.com/questions/7527982/applying-gitignore-to-committed-files

**Pull request merged**
